CREATE TABLE "Clients" (
	"idAccount" INTEGER NOT NULL UNIQUE,
	"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("idAccount")
);




CREATE TABLE "Cards" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL,
	"idBusiness" INTEGER NOT NULL,
	"expiration" BIGINT NOT NULL,
	"maxStamp" INTEGER NOT NULL,
	"description" VARCHAR(2000) NOT NULL,
	"restrictions" VARCHAR(500) NOT NULL,
	"reward" VARCHAR(500) NOT NULL,
	"isActive" BOOLEAN NOT NULL DEFAULT true,
	"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE "Business" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(100),
	"description" VARCHAR(1000),
	"email" VARCHAR(255),
	"logoImage" VARCHAR(500),
  "bannerImage" VARCHAR(500),
	"address" VARCHAR(250),
	"fullInformation" BOOLEAN NOT NULL DEFAULT false,
	"rating_average" REAL NOT NULL DEFAULT 0,
	"rating_count" INTEGER NOT NULL DEFAULT 0,
	"location_latitude" DECIMAL(11,8),
	"location_longitude" DECIMAL(11,8),
	"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE "Categories" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE "Links" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE "Ratings" (
	"id" SERIAL NOT NULL UNIQUE,
	"idClient" INTEGER NOT NULL,
	"idBusiness" INTEGER NOT NULL,
	"valoration" SMALLINT NOT NULL DEFAULT 5 CHECK (valoration >= 1 AND valoration <= 5),
	PRIMARY KEY("id")
);




CREATE TABLE "Plans" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE "CardStates" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE "Notifications" (
	"id" SERIAL NOT NULL UNIQUE,
	"content" VARCHAR(500) NOT NULL,
	"link" VARCHAR(500),
	PRIMARY KEY("id")
);




CREATE TABLE "CardsClients" (
	"id" SERIAL NOT NULL UNIQUE,
	"idClient" INTEGER NOT NULL,
	"idCard" INTEGER NOT NULL,
	"idCardState" INTEGER NOT NULL,
	"expirationDate" TIMESTAMP NOT NULL,
	"currentStamps" INTEGER NOT NULL,
	"UniqueCode" CHAR(8) UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE "AccountsNotifications" (
	"id" SERIAL NOT NULL UNIQUE,
	"idNotification" INTEGER NOT NULL,
	"idAccount" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE "Collaborators" (
	"idAccount" INTEGER NOT NULL,
	"idBusiness" INTEGER NOT NULL,
	"idRol" INTEGER NOT NULL,
	PRIMARY KEY("idAccount", "idBusiness")
);




CREATE TABLE "BusinessCategories" (
	"idBusiness" INTEGER NOT NULL,
	"idCategory" INTEGER NOT NULL,
	PRIMARY KEY("idBusiness", "idCategory")
);




CREATE TABLE "CollaboratorsActivities" (
	"id" SERIAL NOT NULL UNIQUE,
	"idAccount" INTEGER NOT NULL,
	"idBusiness" INTEGER NOT NULL,
	"idActionType" INTEGER NOT NULL,
	"value" INTEGER,
	"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE "ActionTypes" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE "AuthProviders" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE "Accounts" (
	"id" SERIAL NOT NULL UNIQUE,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"fullName" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255),
	"idAuthProvider" INTEGER NOT NULL,
	"isActive" BOOLEAN NOT NULL DEFAULT true,
	"providerUserId" VARCHAR(255),
	"emailVerified" BOOLEAN NOT NULL DEFAULT false,
	"profileImageURL" VARCHAR(500),
	"refreshToken" VARCHAR(500),
	PRIMARY KEY("id")
);




CREATE TABLE "Roles" (
	"id" SERIAL NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE "Subscriptions" (
	"id" SERIAL NOT NULL UNIQUE,
	"idBusiness" INTEGER NOT NULL,
	"idPlan" INTEGER NOT NULL,
	"startDate" TIMESTAMP NOT NULL,
	"endDate" TIMESTAMP,
	"creationDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE "FavoritesBusiness" (
	"id" SERIAL NOT NULL UNIQUE,
	"idBusiness" INTEGER NOT NULL,
	"idClient" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE "BusinessLink" (
	"idLInk" INTEGER NOT NULL,
	"idBusiness" INTEGER NOT NULL,
	"value" VARCHAR(255) NOT NULL,
	PRIMARY KEY("idLInk", "idBusiness")
);



ALTER TABLE "AccountsNotifications"
ADD FOREIGN KEY("idNotification") REFERENCES "Notifications"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "CardsClients"
ADD FOREIGN KEY("idCardState") REFERENCES "CardStates"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "CardsClients"
ADD FOREIGN KEY("idClient") REFERENCES "Clients"("idAccount")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "CardsClients"
ADD FOREIGN KEY("idCard") REFERENCES "Cards"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "BusinessCategories"
ADD FOREIGN KEY("idCategory") REFERENCES "Categories"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "BusinessCategories"
ADD FOREIGN KEY("idBusiness") REFERENCES "Business"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Ratings"
ADD FOREIGN KEY("idBusiness") REFERENCES "Business"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Ratings"
ADD FOREIGN KEY("idClient") REFERENCES "Clients"("idAccount")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Collaborators"
ADD FOREIGN KEY("idBusiness") REFERENCES "Business"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Cards"
ADD FOREIGN KEY("idBusiness") REFERENCES "Business"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "CollaboratorsActivities"
ADD FOREIGN KEY("idBusiness") REFERENCES "Business"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "CollaboratorsActivities"
ADD FOREIGN KEY("idActionType") REFERENCES "ActionTypes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Accounts"
ADD FOREIGN KEY("idAuthProvider") REFERENCES "AuthProviders"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Clients"
ADD FOREIGN KEY("idAccount") REFERENCES "Accounts"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Collaborators"
ADD FOREIGN KEY("idAccount") REFERENCES "Accounts"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Collaborators"
ADD FOREIGN KEY("idRol") REFERENCES "Roles"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "CollaboratorsActivities"
ADD FOREIGN KEY("idAccount") REFERENCES "Accounts"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "AccountsNotifications"
ADD FOREIGN KEY("idAccount") REFERENCES "Accounts"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Subscriptions"
ADD FOREIGN KEY("idBusiness") REFERENCES "Business"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Subscriptions"
ADD FOREIGN KEY("idPlan") REFERENCES "Plans"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "FavoritesBusiness"
ADD FOREIGN KEY("idClient") REFERENCES "Clients"("idAccount")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "FavoritesBusiness"
ADD FOREIGN KEY("idBusiness") REFERENCES "Business"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "BusinessLink"
ADD FOREIGN KEY("idLInk") REFERENCES "Links"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "BusinessLink"
ADD FOREIGN KEY("idBusiness") REFERENCES "Business"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
