services:
  db:
    image: postgres:13-alpine
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dbSchema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./ddl.sql:/docker-entrypoint-initdb.d/02-ddl.sql
      - ./functions.sql:/docker-entrypoint-initdb.d/03-functions.sql
      - ./triggers.sql:/docker-entrypoint-initdb.d/04-triggers.sql
volumes:
  db_data:
